### ISSUE TITLE
Using on a live microphone source

### ISSUE THREAD

**Issue by MadlyFX** [bitfocus/libltc-wrapper#19]
Hi! Have you had any luck decoding timecode live, from a microphone source?

**Comment by haakonnessjoen** [comment]
Yes, we have tested on live shows, not via microphone, but from a line-signal from other equipment that is connected together.

**Comment by MadlyFX** [comment]
Thanks! Do you have any recommendations for an nodejs library to get that audio in?

**Comment by haakonnessjoen** [comment]
You could check out https://github.com/Streampunk/naudiodon
